### ISSUE TITLE
(improvement) Fetch the solution file and test file from .meta/config.json

### ISSUE THREAD

**Issue by glennj** [exercism/bash-test-runner#31]
Instead of building those filenames in run.sh, simply extract them from the exercise's config.

This will remove the need to first check if the test file is `*.bats` and if not using `*_test.sh`.

This will future-proof us if we want to change the solution from `*.sh` to `*.bash` or remove the extension entirely.

**Comment by glennj** [comment]
@ErikSchierboom I was working on this today. Testing in docker resulted in test failures. Is the solution's `.exercism/config.json` available in the solution directory?

I haven't figured out if the `--mount` option also provides subdirectories.

**Comment by ErikSchierboom** [comment]
@glennj For the test runner, it is located in the `.meta/config.json` directory. The `--mount` option does provide sub-directories IIRC.
